### ISSUE TITLE
can't build for lack of file

### ISSUE THREAD

**Issue by pzz2011** [huawei-noah/streamDM-Cpp#2]
> code/src/core/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/core/../Common.h:43:0,
>                  from code/src/core/InstanceInformation.cpp:20:
> code/src/core/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/core/../Common.h:43:0,
>                  from code/src/core/SparseInstance.cpp:26:
> code/src/core/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/utils/Log.cpp:18:0:
> code/src/utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/utils/../Common.h:43:0,
>                  from code/src/utils/CommandLineParser.cpp:20:
> code/src/utils/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/utils/../Common.h:43:0,
>                  from code/src/utils/Configurable.cpp:19:
> code/src/utils/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/utils/LearnerModel.cpp:19:0:
> code/src/utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/streams/../Common.h:43:0,
>                  from code/src/streams/ArffReader.h:21,
>                  from code/src/streams/ArffReader.cpp:18:
> code/src/streams/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/streams/../Common.h:43:0,
>                  from code/src/streams/C45Reader.h:21,
>                  from code/src/streams/C45Reader.cpp:18:
> code/src/streams/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/streams/../Common.h:43:0,
>                  from code/src/streams/CSVReader.cpp:27:
> code/src/streams/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/streams/../Common.h:43:0,
>                  from code/src/streams/LibSVMReader.h:30,
>                  from code/src/streams/LibSVMReader.cpp:25:
> code/src/streams/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/evaluation/../Common.h:43:0,
>                  from code/src/evaluation/BasicClassificationEvaluator.cpp:19:
> code/src/evaluation/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/evaluation/../Common.h:43:0,
>                  from code/src/evaluation/NullEvaluator.cpp:19:
> code/src/evaluation/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/../Common.h:43:0,
>                  from code/src/learners/Learner.cpp:19:
> code/src/learners/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Functions/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Functions/Logisticregression.cpp:19:
> code/src/learners/Classifiers/Functions/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Functions/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Functions/Majorityclass.cpp:2:
> code/src/learners/Classifiers/Functions/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Functions/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Functions/Perceptron.cpp:19:
> code/src/learners/Classifiers/Functions/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Bayes/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Bayes/Naivebayes.cpp:20:
> code/src/learners/Classifiers/Bayes/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Bayes/observer/../../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Bayes/observer/NumericAttributeClassObserver.h:22,
>                  from code/src/learners/Classifiers/Bayes/SimpleNaiveBayesStatistics.cpp:19:
> code/src/learners/Classifiers/Bayes/observer/../../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Meta/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Meta/Bagging.cpp:20:
> code/src/learners/Classifiers/Meta/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Bayes/observer/../../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Bayes/observer/NominalAttributeClassObserver.h:22,
>                  from code/src/learners/Classifiers/Bayes/observer/NominalAttributeClassObserver.cpp:18:
> code/src/learners/Classifiers/Bayes/observer/../../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Bayes/observer/../../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Bayes/observer/NumericAttributeClassObserver.h:22,
>                  from code/src/learners/Classifiers/Bayes/observer/NumericAttributeClassObserver.cpp:18:
> code/src/learners/Classifiers/Bayes/observer/../../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Trees/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Trees/ADWIN.h:23,
>                  from code/src/learners/Classifiers/Trees/ADWIN.cpp:18:
> code/src/learners/Classifiers/Trees/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Trees/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Trees/InstanceConditionalTest.h:22,
>                  from code/src/learners/Classifiers/Trees/AttributeSplitSuggestion.h:22,
>                  from code/src/learners/Classifiers/Trees/AttributeSplitSuggestion.cpp:18:
> code/src/learners/Classifiers/Trees/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Trees/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Trees/HTNode.h:24,
>                  from code/src/learners/Classifiers/Trees/HATNode.h:25,
>                  from code/src/learners/Classifiers/Trees/HATNode.cpp:18:
> code/src/learners/Classifiers/Trees/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Trees/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Trees/HoeffdingTree.h:24,
>                  from code/src/learners/Classifiers/Trees/HoeffdingAdaptiveTree.h:23,
>                  from code/src/learners/Classifiers/Trees/HoeffdingAdaptiveTree.cpp:19:
> code/src/learners/Classifiers/Trees/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Trees/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Trees/HoeffdingTree.h:24,
>                  from code/src/learners/Classifiers/Trees/HoeffdingTree.cpp:18:
> code/src/learners/Classifiers/Trees/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Trees/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Trees/InstanceConditionalTest.h:22,
>                  from code/src/learners/Classifiers/Trees/AttributeSplitSuggestion.h:22,
>                  from code/src/learners/Classifiers/Trees/HTAttributeClassObserver.h:23,
>                  from code/src/learners/Classifiers/Trees/HTAttributeClassObserver.cpp:18:
> code/src/learners/Classifiers/Trees/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Trees/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Trees/HTNode.h:24,
>                  from code/src/learners/Classifiers/Trees/HTNode.cpp:18:
> code/src/learners/Classifiers/Trees/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/learners/Classifiers/Trees/../../../Common.h:43:0,
>                  from code/src/learners/Classifiers/Trees/InstanceConditionalTest.h:22,
>                  from code/src/learners/Classifiers/Trees/InstanceConditionalTest.cpp:18:
> code/src/learners/Classifiers/Trees/../../../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/tasks/../Common.h:43:0,
>                  from code/src/tasks/EvaluatePrequential.h:21,
>                  from code/src/tasks/EvaluatePrequential.cpp:18:
> code/src/tasks/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/tasks/../Common.h:43:0,
>                  from code/src/tasks/EvaluateHoldOut.h:21,
>                  from code/src/tasks/EvaluateHoldOut.cpp:19:
> code/src/tasks/../utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> In file included from code/src/Common.h:43:0,
>                  from code/src/main.cpp:18:
> code/src/utils/Log.h:26:31: fatal error: log4cpp/Category.hh: No such file or directory
>  #include <log4cpp/Category.hh>
>                                ^
> compilation terminated.
> makefile:80: recipe for target 'all' failed
> make: **\* [all] Error 1

excuse for interrupt you, can you give me some useful advice to build streamDM-cpp?

**Comment by Koushik667** [comment]
you need to install log4cpp,may be this link will help:
http://programmingknowledgeblog.blogspot.com/2013/01/build-and-run-sample-code-using-log4cpp.html
